source 'https://rubygems.org'

gem 'acts_as_list'
gem 'bootsnap'
gem 'bootstrap-sass'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '~> 5.2.0'
gem 'sass-rails', '~> 5.0.6'
gem 'sqlite3', '~> 1.3.6'
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'listen', '>= 3.0.5'
end
